[tool.autopep8]
max_line_length = 120
ignore = ["E501"]
in-place = true
recursive = true
aggressive = 1

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = false

[tool.pylsp]
plugins.pycodestyle.enabled = true
plugins.pycodestyle.maxLineLength = 120
plugins.autopep8.enabled = true
plugins.yapf.enabled = false
plugins.black.enabled = false
plugins.pyflakes.enabled = true
plugins.pylint.enabled = false
plugins.mccabe.enabled = true
plugins.mccabe.threshold = 10

[tool.pycodestyle]
max_line_length = 120
ignore = ["E501", "W503"]
